server {
    listen 80;
    server_name y1g0ul.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name y1g0ul.ru;

    ssl_certificate /etc/letsencrypt/live/y1g0ul.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/y1g0ul.ru/privkey.pem;

    location / {
        proxy_pass http://web:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
